config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :items, :only => [:new, :create, :edit, :update]
    delete 'clear', :on => :member
  end
  root 'projects#index'
end

app/models/concerns/soft_deletable.rb
require 'active_support/concern'

module SoftDeletable
  extend ActiveSupport::Concern

  def soft_delete
    update(deleted: true)
  end

  module ClassMethods
    # ar_collection is an ActiveRecord_AssociationRelation object
    def soft_delete_all(ar_collection)
      ar_collection.each { |e| e.soft_delete }
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include SoftDeletable

  belongs_to :project
  validates :action,
    :presence => true,
    :uniqueness => { :scope => :project,
                     :message => 'should be unique within a project' }
  validates :project_id, :presence => true
  scope :complete, -> { where(:done => true) }
  scope :complete_and_undeleted, -> { where(:done => true, :deleted => false) }
end

app/models/project.rb
class Project < ActiveRecord::Base
  include SoftDeletable

  validates :title, :presence => true, :uniqueness => true
  has_many :items, :dependent => :destroy

  def uncleared_items
    items.where(deleted: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_project
  before_action :set_item, only: [:edit, :update]
  before_action :set_breadcrumb

  def set_breadcrumb
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @project.title, project_path(@project)
  end

  def new
    @item = @project.items.build

    add_breadcrumb 'New Item'
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully created.' }
      else
        format.html { render :action => 'new' }
        add_breadcrumb "New Item"
      end
    end
  end

  def edit
    add_breadcrumb @item.action
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully updated.' }
      else
        format.html { render :action => 'edit' }
        add_breadcrumb @item.action_was
      end
    end
  end

private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_item
    @item = @project.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, :except => [:index, :new, :create]
  before_action :set_breadcrumb

  def set_breadcrumb
    add_breadcrumb "Projects", :root_path
    add_breadcrumb @project.title, project_path(@project) if @project
  end

  def index
    @projects = Project.where(deleted: false)
  end

  def show
  end

  def new
    @project = Project.new
    add_breadcrumb "New Project", new_project_path
  end

  def edit
    add_breadcrumb @project.title
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully created.' }
      else
        format.html { render :action => 'new' }
        add_breadcrumb "New Project"
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully updated.' }
      else
        format.html { render :action => 'edit' }
        add_breadcrumb @project.title_was
      end
    end
  end

  def destroy
    @project.soft_delete
    respond_to do |format|
      format.html { redirect_to projects_path,
                    :notice => 'Project was successfully destroyed.' }
    end
  end

  def clear
    cleared_projects = Project.soft_delete_all(@project.items.complete_and_undeleted)

    respond_to do |format|
      format.html { redirect_to project_path(@project),
        :notice => cleared_flash_message(cleared_projects: cleared_projects) }
    end
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end

  def cleared_flash_message(cleared_projects:)
    if cleared_projects.any?
      'Completed items were successfully cleared.'
    else
      'There are no completed items for this project.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # https://gist.github.com/suryart/7418454
  def bootstrap_class_for flash_type
    { success: "alert-success",
      error:   "alert-danger",
      alert:   "alert-warning",
      notice:  "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message,
      class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/views/items/_form.html.erb
<%= simple_form_for([@project, @item]) do |f| %>
  <%= f.input :action %>
  <%= f.button :submit %>
<% end %>

app/views/items/_index.html.erb
<ul>
  <% if @project.items.where(deleted: false).empty? %>
    <li>No items.</li>
  <% end %>

  <% @project.uncleared_items.each do |item| %>
    <li class="<%= "#{item.done? ? 'done' : 'not-done'}" %>">
      <%= link_to item.action, edit_project_item_path(@project, item) %>

      <% unless item.done? %>
      —
        <%= link_to 'Mark as Completed',
              { :controller => :items,
                :action     => :update,
                :id         => item.id,
                :project_id => @project.id,
                :item       => { :done => true } },
                { :method   => :patch } %>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <%= link_to 'New Item', new_project_item_path(@project), class: "btn btn-primary" %>

  <%= link_to 'Clear Completed Items', clear_project_path(project), class: "btn btn-default", :method => :delete, :id => "clearer" %>
</div>

app/views/items/edit.html.erb
<%= render partial: 'form', locals: { project: @project, item: @item } %>

app/views/items/new.html.erb
<%= render partial: 'form', locals: { project: @project, item: @item } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Todo App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <h1>Todo app</h1>
      </div>

      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <%= render_breadcrumbs %>
          </li>
        </ol>
      </nav>

      <%= flash_messages %>

      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="footer">
      <p>2015</p>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<table class="table table-striped table-hover">
  <% if @projects.empty? %>
    <li>No projects.</li>
  <% end %>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <%= link_to project.title, project_path(project) %>
        </td>

        <td>
          <%= link_to 'Destroy', project,
                      method: :delete, data: { confirm: 'For real?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= link_to 'Edit Project', edit_project_path(@project) %>

<h3>Items</h3>
<%= render partial: 'items/index', :locals => { :project => @project } %>